### ISSUE TITLE
Email template can't have <html> top level tag in Meteor 1.3

### ISSUE THREAD

**Issue by jshimko** [reactioncommerce/launchdock-connect#12] opened 2016-02-18 13:36 UTC
As reported by @newsiberian on Feb 18 in Gitter, this email template:

https://github.com/reactioncommerce/launchdock-connect/blob/development/server/templates/verify_email.html

throws the following error in Meteor 1.3:

```sh
 packages/reactioncommerce:launchdock-connect/server/templates/verify_email.html:1:
   Expected one of: <body>, <head>, <template>
```

Presumably, we just have to remove the top level <html> tags.

**Comment by aaronjudd** [comment] 2016-08-04 16:33
What is the status of this, and could it be moved into a Reaction issue, along with other launchdock-connect related issues?

**Comment by aaronjudd** [comment] 2016-08-04 16:36
I think this is a duplicate of https://github.com/reactioncommerce/reaction/issues/1059, closing this in favor of that general reaction issue.

**Closed by aaronjudd** 2016-08-04 16:36 UTC
Labels: bug, ready
